<script lang="ts">
    import LargeSvgLogo from "$lib/icons/+largeSvgLogo.svelte";
    import GenericModal from "$lib/modals/+GenericModal.svelte";
</script>

<h1 class="text-neutral-300 text-xl m-5">Sample Text</h1>
<GenericModal />
<!-- not working for some reason -->
<LargeSvgLogo />

<p class=" text-white" >
    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nulla porttitor massa id neque. Nisl rhoncus mattis rhoncus urna neque viverra. Habitasse platea dictumst quisque sagittis purus sit. Ornare arcu odio ut sem nulla pharetra diam sit. Condimentum vitae sapien pellentesque habitant. Pellentesque nec nam aliquam sem et tortor consequat id. Odio ut sem nulla pharetra diam. Nec dui nunc mattis enim ut. Erat imperdiet sed euismod nisi. Sodales ut eu sem integer vitae justo eget. Sodales neque sodales ut etiam sit amet nisl.

    Morbi leo urna molestie at elementum eu facilisis. Lectus sit amet est placerat in egestas erat imperdiet. Vitae suscipit tellus mauris a diam maecenas sed enim ut. Arcu odio ut sem nulla pharetra diam sit amet. Massa sed elementum tempus egestas sed sed risus pretium. Diam in arcu cursus euismod quis viverra nibh cras. Id porta nibh venenatis cras. Orci phasellus egestas tellus rutrum tellus pellentesque eu tincidunt tortor. Scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique. Donec enim diam vulputate ut. Sit amet purus gravida quis blandit turpis. Amet consectetur adipiscing elit ut aliquam.
    
    Nisl vel pretium lectus quam id leo in vitae. Nisl tincidunt eget nullam non nisi est sit. Eu turpis egestas pretium aenean pharetra magna ac placerat. Sit amet consectetur adipiscing elit ut aliquam purus sit amet. Eros in cursus turpis massa tincidunt. Vulputate ut pharetra sit amet aliquam id. Pharetra vel turpis nunc eget lorem dolor. Massa sapien faucibus et molestie ac feugiat sed lectus vestibulum. Nunc scelerisque viverra mauris in aliquam sem fringilla ut. Nibh praesent tristique magna sit amet purus. Porta lorem mollis aliquam ut. Fermentum leo vel orci porta non pulvinar. Ut sem nulla pharetra diam. Amet justo donec enim diam vulputate. Velit ut tortor pretium viverra suspendisse.
    
    Volutpat blandit aliquam etiam erat velit scelerisque. Id aliquet lectus proin nibh nisl condimentum id. Tempus urna et pharetra pharetra massa massa ultricies. Imperdiet massa tincidunt nunc pulvinar sapien et. Egestas pretium aenean pharetra magna ac placerat vestibulum lectus mauris. Ultricies mi eget mauris pharetra et ultrices neque ornare. Elementum facilisis leo vel fringilla est ullamcorper eget. Ullamcorper sit amet risus nullam eget felis eget nunc lobortis. Ornare lectus sit amet est. Nullam non nisi est sit amet facilisis magna etiam.
    
    Ultrices sagittis orci a scelerisque purus semper eget duis. Sit amet justo donec enim diam vulputate. Diam volutpat commodo sed egestas egestas. Aliquam ultrices sagittis orci a scelerisque purus semper eget duis. Posuere lorem ipsum dolor sit. Cursus euismod quis viverra nibh cras. Sit amet commodo nulla facilisi. Eu non diam phasellus vestibulum lorem sed risus ultricies tristique. Egestas diam in arcu cursus euismod quis viverra. Fames ac turpis egestas integer. Praesent tristique magna sit amet. Sagittis vitae et leo duis ut diam quam. Magna sit amet purus gravida quis blandit turpis. Nibh praesent tristique magna sit amet purus gravida quis. Dictumst quisque sagittis purus sit amet volutpat consequat. Cras ornare arcu dui vivamus arcu felis bibendum ut.
    
    A pellentesque sit amet porttitor eget. Augue mauris augue neque gravida in fermentum et sollicitudin. Arcu vitae elementum curabitur vitae nunc sed. Ante metus dictum at tempor. Mi tempus imperdiet nulla malesuada. Egestas tellus rutrum tellus pellentesque eu tincidunt tortor aliquam nulla. Et odio pellentesque diam volutpat. Ultricies tristique nulla aliquet enim tortor at auctor urna nunc. Tincidunt praesent semper feugiat nibh sed. Turpis egestas maecenas pharetra convallis posuere morbi. Etiam sit amet nisl purus in mollis. Mi tempus imperdiet nulla malesuada. Tristique et egestas quis ipsum suspendisse ultrices gravida dictum fusce. Scelerisque fermentum dui faucibus in ornare quam viverra orci. Vitae tempus quam pellentesque nec nam aliquam sem. Etiam dignissim diam quis enim lobortis scelerisque. Auctor eu augue ut lectus arcu bibendum.
    
    Blandit cursus risus at ultrices mi tempus. Quam nulla porttitor massa id neque aliquam. Posuere urna nec tincidunt praesent semper feugiat. Penatibus et magnis dis parturient montes nascetur ridiculus mus. Sapien faucibus et molestie ac feugiat sed lectus vestibulum mattis. Quis blandit turpis cursus in hac habitasse platea dictumst quisque. Malesuada nunc vel risus commodo viverra maecenas accumsan lacus. Placerat vestibulum lectus mauris ultrices eros in cursus turpis. Auctor urna nunc id cursus metus. Faucibus nisl tincidunt eget nullam. Diam quis enim lobortis scelerisque fermentum dui faucibus in ornare. Proin libero nunc consequat interdum varius sit amet mattis vulputate. Ullamcorper velit sed ullamcorper morbi tincidunt. Auctor neque vitae tempus quam. Pellentesque massa placerat duis ultricies lacus.
    
    At tempor commodo ullamcorper a lacus vestibulum sed arcu. Mi sit amet mauris commodo quis imperdiet. Nec nam aliquam sem et tortor. Ipsum nunc aliquet bibendum enim facilisis gravida neque. Egestas purus viverra accumsan in nisl nisi scelerisque. Quis enim lobortis scelerisque fermentum dui faucibus in. Sit amet nisl suscipit adipiscing bibendum est ultricies integer. Aliquet lectus proin nibh nisl condimentum id venenatis a condimentum. In arcu cursus euismod quis viverra. Eget aliquet nibh praesent tristique magna sit. Odio ut sem nulla pharetra diam sit. Nisi vitae suscipit tellus mauris a. Lobortis mattis aliquam faucibus purus in massa. Vestibulum lectus mauris ultrices eros in cursus turpis massa. Odio ut sem nulla pharetra diam sit amet nisl suscipit. Risus ultricies tristique nulla aliquet enim tortor at. Penatibus et magnis dis parturient montes nascetur ridiculus mus mauris. Odio morbi quis commodo odio aenean sed adipiscing diam donec.
    
    Faucibus ornare suspendisse sed nisi. Nisi lacus sed viverra tellus in hac habitasse. Libero justo laoreet sit amet cursus sit amet dictum. Sem fringilla ut morbi tincidunt augue interdum velit euismod. Enim nulla aliquet porttitor lacus luctus. Sed sed risus pretium quam vulputate. Morbi enim nunc faucibus a pellentesque. Fermentum iaculis eu non diam. Mauris ultrices eros in cursus turpis massa tincidunt dui. Nunc sed augue lacus viverra. Nibh mauris cursus mattis molestie a iaculis. Vitae et leo duis ut diam. Interdum consectetur libero id faucibus nisl tincidunt eget nullam. Diam quam nulla porttitor massa. Proin fermentum leo vel orci porta non pulvinar. Proin fermentum leo vel orci porta non pulvinar neque.
    
    Mi quis hendrerit dolor magna eget est lorem ipsum. Quam id leo in vitae turpis massa sed elementum. Vel turpis nunc eget lorem dolor sed viverra ipsum. A cras semper auctor neque vitae tempus quam pellentesque. Cras sed felis eget velit aliquet sagittis id consectetur purus. Sed cras ornare arcu dui vivamus. Enim nunc faucibus a pellentesque sit amet porttitor eget dolor. Quam lacus suspendisse faucibus interdum. Pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Orci porta non pulvinar neque laoreet suspendisse. Sed velit dignissim sodales ut. Diam vulputate ut pharetra sit amet aliquam id diam maecenas. Et sollicitudin ac orci phasellus egestas tellus. Sed odio morbi quis commodo odio. Id volutpat lacus laoreet non curabitur gravida arcu ac tortor. Condimentum lacinia quis vel eros donec ac. Non diam phasellus vestibulum lorem sed risus. Nunc aliquet bibendum enim facilisis gravida. Et malesuada fames ac turpis egestas. Pulvinar etiam non quam lacus suspendisse faucibus interdum.
</p>